name: Build and Test .NET 6.0

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build-and-test:
    name: build-and-test-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [windows-latest]    
        include:
          - framework: 'net6.0'
            dotnet-version: '6.0.x'
            configuration: 'Release'
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build
      run: dotnet build --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} "DaAeHdaNetStandard.sln"
      
    - name: Test
      # note: /p:CollectCoverage=true is only used to disable deterministc builds
      # run: dotnet test --no-build --framework ${{ matrix.framework }} --logger trx --configuration ${{ matrix.configuration }} /p:CollectCoverage=true --collect:"XPlat Code Coverage" --settings ./Tests/coverlet.runsettings.xml --results-directory "TestResults-${{matrix.os}}-${{matrix.framework}}-${{matrix.configuration}}" "OpcUaSolutionNet.sln"
   
