name: Build and Test .NET 7.0

on:
  push:
  pull_request:
    branches: [ master ]
    paths:
    - '**.cs'
    - '**.csproj'

env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'

jobs:
  build-and-test-net7:
    name: build-and-test-net7-${{matrix.os}}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false    
      matrix:
        os: [windows-latest]    
        include:
          - framework: 'net7.0-windows'
            dotnet-version: '7.0.x'
            configuration: 'Release'
            
    env:
      OS: ${{ matrix.os }}
      DOTNET_VERSION: ${{ matrix.dotnet-version }}
      CONFIGURATION:  ${{ matrix.configuration }}
      
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    
    - name: Setup .NET ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
        
    - name: Build DaAeHdaNetStandard.sln
      run: dotnet build --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} "DaAeHdaNetStandard.sln"

    - name: Build WorkshopClientSamples.sln
      run: dotnet build --force --framework ${{ matrix.framework }} --configuration ${{ matrix.configuration }} "WorkshopClientSamples.sln"
